<?php

namespace Miky\Bundle\CommercialBundle\Repository;

/**
 * ContactSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
