miky_commercial.admin.contact_sheet:
    resource: |
        alias: miky_commercial.contact_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_commercial.admin.contact_sheet
        form: Miky\Bundle\CommercialBundle\Form\Type\Admin\ContactSheetAdminType
        permission: true
        vars:
            all:
                subheader: miky_commercial.contact_sheets.manage
            index:
                icon: cube
    type: miky.resource_admin

miky_commercial.admin.company_sheet:
    resource: |
        alias: miky_commercial.company_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_commercial.admin.contact_sheet
        form: Miky\Bundle\CommercialBundle\Form\Type\Admin\CompanySheetAdminType
        permission: true
        vars:
            all:
                subheader: miky_commercial.company_sheets.manage
            index:
                icon: cube
    type: miky.resource_admin