miky_commercial.admin.contact_sheet:
    resource: |
        alias: miky_commercial.contact_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_commercial.admin.contact_sheet
        form: Miky\Bundle\CommercialBundle\Form\Type\Admin\ContactSheetAdminType
        permission: true
        vars:
            all:
                subheader: miky_commercial.contact_sheets.manage
            index:
                icon: cube
    type: miky.resource_admin

miky_commercial.admin.company_sheet:
    resource: |
        alias: miky_commercial.company_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_commercial.admin.company_sheet
        form: Miky\Bundle\CommercialBundle\Form\Type\Admin\CompanySheetAdminType
        permission: true
        vars:
            all:
                subheader: miky_commercial.company_sheets.manage
            index:
                icon: cube
    type: miky.resource_admin


miky_commercial.admin.commercial_action:
    resource: |
        alias: miky_commercial.commercial_action
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_commercial.admin.commercial_action
        form: Miky\Bundle\CommercialBundle\Form\Type\Admin\CommercialActionAdminType
        permission: true
        vars:
            all:
                subheader: miky_commercial.commercial_actions.manage
            index:
                icon: cube
    type: miky.resource_admin



miky_commercial.admin.commercial_action_timeline:
    path: /%miky_admin.admin_path%/timeline
    methods: [GET]
    defaults:
        _controller: miky_commercial.controller.admin.commercial_action:timelineAction
        _seestock:
            alias: miky_commercial.commercial_action
            section: admin
            template: SeestockAdminBundle:Crud:index.html.twig
            type: seestock.resource