miky_commercial.admin.contact_sheet:
    resource: |
        alias: miky_commercial.contact_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.user
        form: miky_user_admin
        permission: true
        vars:
            all:
                subheader: miky_user.manage_users
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin

miky_commercial.admin.company_sheet:
    resource: |
        alias: miky_commercial.company_sheet
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_user.admin.user
        form: miky_user_admin
        permission: true
        vars:
            all:
                subheader: miky_user.manage_users
                templates:
                    #form: MikyAdminBundle:Product:_form.html.twig
            index:
                icon: cube
    type: miky.resource_admin